components_manager:
    task_processors:
        main-task-processor:          # Main task processor for CPU-bound tasks
            worker_threads: 4
        fs-task-processor:            # Required task processor for file system operations
            worker_threads: 2

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: 8080
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: "logs/default.log"
                    level: debug
                    overflow_behavior: discard
                info:
                    file_path: "logs/info.log"
                    level: info
                    overflow_behavior: discard
                error:
                    file_path: "logs/error.log"
                    level: error
                    overflow_behavior: discard
                debug:
                    file_path: "logs/debug.log"
                    level: debug
                    overflow_behavior: discard

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-hello:
            path: /hello
            method: GET,POST
            task_processor: main-task-processor